import type { MazeData } from "./types"

export function getInitialMazes(): MazeData[] {
    return [
        {
            id: "maze1",
            name: "基本の迷路",
            size: 5,
            grid: [
                ["start", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "wall", "floor", "wall"],
                ["floor", "floor", "floor", "floor", "wall"],
                ["floor", "wall", "wall", "wall", "wall"],
                ["floor", "floor", "floor", "floor", "goal"],
            ],
        },
        {
            id: "maze2",
            name: "穴のある迷路",
            size: 5,
            grid: [
                ["start", "floor", "hole", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "wall"],
                ["wall", "floor", "wall", "floor", "wall"],
                ["wall", "floor", "hole", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "goal"],
            ],
        },
        {
            id: "maze3",
            name: "ループ練習",
            size: 6,
            grid: [
                ["start", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "wall", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "floor", "wall", "wall", "wall", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "goal"],
                ["wall", "wall", "wall", "wall", "wall", "wall"],
            ],
        },
        {
            id: "maze4",
            name: "複雑な迷路",
            size: 7,
            grid: [
                ["start", "floor", "wall", "floor", "floor", "floor", "wall"],
                ["floor", "floor", "wall", "floor", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "wall", "floor", "wall"],
                ["wall", "wall", "wall", "floor", "hole", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "floor", "wall", "wall", "wall", "floor", "goal"],
                ["wall", "wall", "wall", "wall", "wall", "wall", "wall"],
            ],
        },
        {
            id: "maze5",
            name: "シンプル",
            size: 5,
            grid: [
                ["start", "floor", "floor", "floor", "goal"],
                ["wall", "wall", "wall", "wall", "wall"],
                ["floor", "floor", "floor", "floor", "floor"],
                ["wall", "wall", "wall", "wall", "wall"],
                ["floor", "floor", "floor", "floor", "floor"],
            ],
        },
        {
            id: "maze6",
            name: "穴だらけ",
            size: 6,
            grid: [
                ["start", "floor", "hole", "floor", "hole", "wall"],
                ["floor", "floor", "floor", "floor", "floor", "wall"],
                ["hole", "floor", "wall", "wall", "floor", "wall"],
                ["floor", "floor", "hole", "floor", "floor", "wall"],
                ["floor", "wall", "floor", "floor", "hole", "floor"],
                ["floor", "floor", "floor", "floor", "floor", "goal"],
            ],
        },
        {
            id: "maze7",
            name: "ジグザグ",
            size: 7,
            grid: [
                ["start", "floor", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "wall", "wall", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "floor", "wall", "wall", "wall", "wall", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "wall", "wall", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "goal"],
            ],
        },
        {
            id: "maze8",
            name: "大きな迷路",
            size: 8,
            grid: [
                ["start", "floor", "floor", "wall", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "floor", "wall", "floor", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "wall", "floor", "wall"],
                ["wall", "floor", "wall", "wall", "floor", "hole", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "floor", "wall"],
                ["wall", "wall", "wall", "floor", "wall", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "floor", "goal"],
                ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
            ],
        },
        {
            id: "maze9",
            name: "スパイラル",
            size: 7,
            grid: [
                ["start", "floor", "floor", "floor", "floor", "floor", "floor"],
                ["wall", "wall", "wall", "wall", "wall", "wall", "floor"],
                ["floor", "floor", "floor", "floor", "floor", "wall", "floor"],
                ["floor", "wall", "wall", "wall", "floor", "wall", "floor"],
                ["floor", "wall", "goal", "floor", "floor", "wall", "floor"],
                ["floor", "wall", "wall", "wall", "wall", "wall", "floor"],
                ["floor", "floor", "floor", "floor", "floor", "floor", "floor"],
            ],
        },
        {
            id: "maze10",
            name: "チャレンジ",
            size: 8,
            grid: [
                ["start", "floor", "hole", "floor", "wall", "floor", "hole", "wall"],
                ["floor", "floor", "floor", "floor", "wall", "floor", "floor", "wall"],
                ["wall", "wall", "floor", "wall", "wall", "wall", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "hole", "floor", "floor", "wall"],
                ["wall", "floor", "wall", "floor", "floor", "floor", "wall", "wall"],
                ["wall", "floor", "wall", "wall", "wall", "floor", "floor", "wall"],
                ["wall", "floor", "floor", "floor", "floor", "floor", "floor", "goal"],
                ["wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall"],
            ],
        },
    ]
}
